### ISSUE TITLE
Samples use hardcoded expiration for SAS tokens

### ISSUE THREAD

**Issue by danewalton** [Azure-Samples/iot-middleware-freertos-samples#133]
Currently the expiration time is hardcoded for SAS token expiration ([example](https://github.com/Azure-Samples/iot-middleware-freertos-samples/blob/40743fabd638961ca8765f8a5d8a8361579ff5e0/demos/projects/ST/b-l475e-iot01a/main.c#L70)).

We should look to update this to platform clock implementation.

**Comment by danewalton** [comment]
Needed for STM32 and NXP samples

**Comment by RLeclair** [comment]
Addressed in #352
