### ISSUE TITLE
Connection breaks after an hour or so

### ISSUE THREAD

**Issue by nexstem-siddhant** [Azure-Samples/iot-middleware-freertos-samples#138]
I am using SAS key for device authentication (ESP32), and after 60 minutes or so, the connection closes. I know that the token expires after 3600 seconds, but shouldn't it be automatically refreshed as the pxTokenRefresh function is initialized in the SetSymmetricKey function call. Do I explicitly need to call Connect method again after the expiration?

**Comment by danewalton** [comment]
Hi @nexstem-siddhant thanks for the question. At this time, the refresh is not done automatically. Application code can take account of this scenario by reissuing a connect when it expires and disconnects. 

We can look into doing this automatically, which would still be a disconnect followed by another connect. But no promises at this point.

It would be great if this could be done without disconnecting, and that's exactly what is possible with MQTT 5 :)
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5#reauthentication
