### ISSUE TITLE
Issue with Group enrollment for X.509 certificate 

### ISSUE THREAD

**Issue by naakhtar** [Azure-Samples/iot-middleware-freertos-samples#225]
Not able to do provisioning Service enrollment group for X.509 certificate attestation.

**Comment by ramanijaldeep** [comment]
Not able to provision the device with enrollment group service for X.509 certificate attestation.

**Comment by danewalton** [comment]
Hi @ramanijaldeep 

1. How are you configuring your certificates? What commands are you using?
2. How are you adding those certificates to your demo config? What format are they in?

**Comment by ramanijaldeep** [comment]
> Hi @ramanijaldeep
> 
> 1. How are you configuring your certificates? What commands are you using?
> 2. How are you adding those certificates to your demo config? What format are they in?

Hi @danewalton 

In sample examples, it is working. I got an error when building an application on FreeRTOS devices.

**Comment by danewalton** [comment]
Sorry your answer is a little confusing to me. Does this mean you don't need help anymore and you have your solution working?

**Comment by danewalton** [comment]
Closing this issue for now due to inactivity. If you would like it reopened, please let us know. For any other questions, please open another Github issue.
