### ISSUE TITLE
Is size chart for ESPRESSIF ESP32 still valid after ADU update?

### ISSUE THREAD

**Issue by RBartonMesh** [Azure-Samples/iot-middleware-freertos-samples#284]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Documentation question:
> at https://github.com/Azure-Samples/iot-middleware-freertos-samples/tree/main/demos/projects/ESPRESSIF/aziotkit#size-chart , detailed Flash and RAM info is given for builds with/without DPS and for either middleware library or total size.
>
> Are these values up-to-date / accurate now that support for ADU i.e. Device Update for IoT Hub has been added?
>
> I checked and this section of the README was not updated by the recent "merge ADU features to main" PR #275

### Any log messages given by the failure
> n/a

### Expected/desired behavior
> The info posted in that Size Chart is accurate / up to date

### OS and Version?
> FreeRTOS

### Versions
> Latest main as of 2022-11-23

### Mention any other details that might be useful

> ---------------------------------------------------------------
> FYI @danewalton

**Comment by danewalton** [comment]
Hi @RBartonMesh we don't yet have the size chart for ADU on the ESP32, but hope to get that out soon.
