### ISSUE TITLE
Getting component not ADU while trying the sample code snippets in a custom application.

### ISSUE THREAD

**Issue by fmadhurakkariyan** [Azure-Samples/iot-middleware-freertos-samples#310]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Trying ADU update with ESP32 with the sample code snippets.

### Any log messages given by the failure
> AZ IOT: Writable properties received: {"desired":{"deviceUpdate":{"__t":"c","service":{"workflow":{"action":255,"id":"nodeployment","retryTimestamp":"2022-12-30T06:29:38.0062502Z"}}},"$version":12},"reported":{"GPS":{"Lat":"10.95432091","Long":"76.32286072"},"FirmwareDetails":{"Version":"1.2","BuildDate":"2022-04-10T06:04:00Z"},"deviceUpdate":{"__t":"c","agent":{"deviceProperties":{"manufacturer":"ESPRESSIF","model":"ESP32","interfaceId":"dtmi:azure:iot:deviceUpdate;1","aduVer":"DU;agent/1.0.0"},"compatPropertyNames":"manufacturer,model","state":0,"installedUpdateId":"{\"provider\":\"Inthings\",\"name\":\"ESP32-2.4\",\"version\":\"1.0\"}","workflow":{"action":255,"id":"nodeployment","retryTimestamp":"2022-12-30T06:29:38.0062502Z"}},"service":{"ac":406,"av":7,"value":{}}},"$version":93}}

>AZ IOT: Properties component name: 
>AZ IOT: Component not ADU:
### Expected/desired behavior
>After receiving the writeable properties, the properties component name should be deviceUpdate 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>ESPIDF 4.4.1

### Mention any other details that might be useful
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by danewalton** [comment]
Hi @fmadhurakkariyan 
Are you getting an empty component from the logs?

**Comment by fmadhurakkariyan** [comment]
Hi @danewalton 
Yes, the logs show an empty component.

**Comment by danewalton** [comment]
And this is an otherwise unaltered sample? You're running it straight from main?

**Comment by fmadhurakkariyan** [comment]
It was a problem with the custom code. It is working now.
