### ISSUE TITLE
ADU groups doesnt appear in Groups and Deployments under Update section 

### ISSUE THREAD

**Issue by Shotariusii** [Azure-Samples/iot-middleware-freertos-samples#366]
Hello, i am using ESP32 ADU project, I am trying to add groups for devices by adding tags in Device Twins. but when i check Groups and Deployments under Update section there is no any Group to deploy update.

 i have successful connection, also I checked that i am sending ADU agent state successfully.
but still there is nothing, message with : There are no groups to display.

**Comment by Shotariusii** [comment]
Can anyone help me to find out what is a problem ? 
i think the problem is Azure Portal side, i am missing something.

**Comment by vaavva** [comment]
@Shotariusii Hello! Could you let me know what commit of the repo you're using?
Have you already uploaded the new update and update manifest to the portal? And does your ADU instance have the correct access set up? https://learn.microsoft.com/en-us/azure/iot-hub-device-update/configure-access-control-device-update?tabs=portal#configure-access-for-azure-device-update-service-principal-in-linked-iot-hub

**Comment by Shotariusii** [comment]
Hello vaavva.
yes i have uploaded the new update and manifest to the portal, and i guess i have access because i got contributor role of all associated service. also I checked Groups and Deployments under Update section from admin's account of azure portal but still wast not available. thats why it makes me think the problem is not related to configuration of access, other wise  admin should see groups at least yea?

that is commit i am using

commit 8b21efabdf7f351b668aa25e938a065e98d3f4d5 (HEAD -> main)
Author: Dane Walton <dawalton@microsoft.com>
Date:   Wed Dec 14 17:58:20 2022 -0500

**Comment by Shotariusii** [comment]
![groupanddeploy1](https://user-images.githubusercontent.com/91596284/232760994-1bdae57d-01d6-4e6c-a599-cfcff75ebdfe.jpg)

I configure access again, i was missing something. so now i am getting this in diagnostic section

**Comment by vaavva** [comment]
@Shotariusii  Try updating to a commit from here or later: https://github.com/Azure-Samples/iot-middleware-freertos-samples/commit/28bfb329456d181e35fb3b6170afb3b68e89798c
There were some changes for the release of ADU that could fix this issue. You might need to delete the update you've already uploaded for this to pick up the device correctly. If that doesn't work, can you send your update manifest (feel free to censor any private data)?

**Comment by Shotariusii** [comment]
I will update, thanks.  I also solved that problem,  I was rewriting  main.c file for esp32 and missed some initialisation function of adu.

**Comment by vaavva** [comment]
@Shotariusii Fyi if you're creating your own implementation for the ADU flow, this documentation might be helpful :)
https://github.com/Azure/azure-iot-middleware-freertos/blob/main/docs/how_to_use_adu_client.md

**Comment by Shotariusii** [comment]
Yes exactly, Thanks, i will check it out..
