### ISSUE TITLE
How to connect more than 1 module?

### ISSUE THREAD

**Issue by deucedevelopment** [Azure-Samples/iot-middleware-freertos-samples#376]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
I'm currently porting a codebase that's based on Azure IoT C SDK. There our devices have multiple modules ( >2 ) and it's a crucial feature for us. I'm looking over the examples and I see that there is AzureIoTHubClientOptions_t which takes module ID, but it only takes one. 
Is there a way to specify multiple module IDs to be used?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vaavva** [comment]
Hello @deucedevelopment! It is not possible to have more than one module per connection, but you could have multiple modules on a device if you open a connection for each. Please see this discussion for some more information: https://github.com/Azure/azure-iot-sdk-c/discussions/2506
