### ISSUE TITLE
cmake commands do not work in Git Bash

### ISSUE THREAD

**Issue by smcd253** [Azure-Samples/iot-middleware-freertos-samples#38]
OS: Windows 10
Commands Run: 
```bash
cmake -G Ninja -DVENDOR=ST -DBOARD=b-l475e-iot01a -Bb-l475e-iot01a .
```
Terminal: Git Bash (inside VS Code)

Notes: I have added ninja to path but git bash does not recognize the location. I have to open up cmd and run the command there.

**Comment by danewalton** [comment]
I was not able to get a repro on this. I have a feeling this was related to a session path that was not up to date? And opening a new cmd pulled in the new path. I'll close this for now and if someone else ends up having a similar problem we can revisit.
