### ISSUE TITLE
Wrong version of CMAKE specified 

### ISSUE THREAD

**Issue by EddieTheHead** [Azure-Samples/iot-middleware-freertos-samples#383]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Install CMAKE 3.13
2. Try to build project

### Any log messages given by the failure
>CMake Error at components/azure-iot-middleware-freertos/CMakeLists.txt:27 (file):
  file does not recognize sub-command REAL_PATH

### Expected/desired behavior
> Program builds

### OS and Version?
> Linux 

### Versions
>

### Mention any other details that might be useful
CMAKE file specifies minimal version as
`cmake_minimum_required(VERSION 3.13)
`
but uses api introduced in CMAKE version 3.19

`file(REAL_PATH <path> <out-var> [BASE_DIRECTORY <dir>] [EXPAND_TILDE])[¶]`(https://cmake.org/cmake/help/latest/command/file.html#real-path)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ericwol-msft** [comment]
#384
