### ISSUE TITLE
Add new certs to Samples

### ISSUE THREAD

**Issue by wduraes** [Azure-Samples/iot-middleware-freertos-samples#99]
Samples for middleware must have server certs updated as per C SDK and Embedded C SDK. They can't have only Baltimore, since this is about to be retired.

**Comment by ryanwinter** [comment]
See https://github.com/Azure-Samples/iot-middleware-freertos-samples/pull/129

**Comment by danewalton** [comment]
The new certs have been added so this can be closed.
